//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShowroomWorkstation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        public string Mark { get; set; }
        public string Model { get; set; }
        public int Horsepower { get; set; }
        public System.DateTime YearOfIssue { get; set; }
        public decimal Price { get; set; }
        public int ID_car { get; set; }
        public int CarTypeFK { get; set; }
        public Nullable<int> OrdersFK { get; set; }
        public byte IsSold { get; set; }
        public int TransmissionFK { get; set; }
    
        public virtual CarType CarType { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual TransmissionsType TransmissionsType { get; set; }
    }
}
