//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShowroomWorkstation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modifications
    {
        public string Color { get; set; }
        public int EngineVolume { get; set; }
        public byte ClimateControl { get; set; }
        public byte OnBoardComputer { get; set; }
        public byte AudioSystem { get; set; }
        public int ID_modification { get; set; }
        public int OrdersFK { get; set; }
        public int CarsFK { get; set; }
        public int TransmissionFK { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual TransmissionsType TransmissionsType { get; set; }
    }
}
